data = {'nodes': ['0', '1', '2', '3'], 'start_node': '0', 'end_node': '3',
        'edges': [('0', '1'), ('1', '2'), ('2', '3')],
        'nodes_labels': {'0': 'switch', '1': 'station', '2': 'switch', '3': 'signal'},
        'capacities': {('0', '0'): 1, ('0', '1'): 1, ('1', '1'): 1, ('1', '2'): 1, ('2', '2'): 1, ('2', '3'): 1},
        'existing_trains': {'ICE_0': {'start': 1,
                                      'traveltimes': {('0', '0'): 1, ('1', '1'): 1, ('2', '2'): 1, ('0', '1'): 1,
                                                      ('1', '2'): 1, ('2', '3'): 1}, 'arrival_times': {'1': 3, '3': 7},
                                      'departure_times': {'1': 4}}, 'RE_0': {'start': 11, 'traveltimes': {('0', '0'): 2,
                                                                                                          ('1', '1'): 2,
                                                                                                          ('2', '2'): 1,
                                                                                                          ('0', '1'): 1,
                                                                                                          ('1', '2'): 1,
                                                                                                          (
                                                                                                          '2', '3'): 1},
                                                                             'arrival_times': {'1': 14, '3': 19},
                                                                             'departure_times': {'1': 16}}},
        'new_trains_traveltimes': {'new_train_s_0': {'start': 5,
                                                     'traveltimes': {('0', '0'): 2, ('0', '1'): 1, ('1', '1'): 2,
                                                                     ('1', '2'): 1, ('2', '2'): 1, ('2', '3'): 1},
                                                     'arrival_times': {'1': 8, '3': 13}, 'departure_times': {'1': 10}}},
        'timehorizon': 22}
